Repository THE-FIRST-DANCE/soomga-backend, pull requests merged in 2024-02, with the labels that each got.

#4 feature/#3-prisma-init
  package.json
  prisma/generated-schema.prisma
  prisma/migrations/20240201103833_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seeds/index.ts
  prisma/seeds/member.seed.ts
  prisma/seeds/users.seed.ts
  src/modules/prisma/prisma.config.ts
  src/modules/prisma/prisma.module.ts
  src/modules/prisma/prisma.service.ts
Labels: ✨ Feature

#8 feat(logger): 데이터베이스나 백엔드에서 발생하는 error, warn, log, info 알아보기 쉽도록 로깅하는 로거 작성
  src/modules/app/app.module.ts
  src/modules/logger/logger.module.ts
  src/modules/logger/logger.service.ts
Labels: ✅ Test

#10 feature/#9-crud-member
  src/modules/app/app.module.ts
  src/modules/members/dto/create-member.dto.ts
  src/modules/members/dto/update-member.dto.ts
  src/modules/members/match.decorator.ts
  src/modules/members/members.controller.spec.ts
  src/modules/members/members.controller.ts
  src/modules/members/members.module.ts
  src/modules/members/members.service.spec.ts
  src/modules/members/members.service.ts
Labels: ✨ Feature, ✅ Test

#12 feature/#5-self-auth
  package.json
  src/configs/config.interface.ts
  src/configs/global.config.ts
  src/exceptions/member.exception.ts
  src/interfaces/auth.interface.ts
  src/modules/app/app.module.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.jwt.strategy.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/swagger.ts
  yarn.lock
Labels: ✨ Feature

#13 feature/#5-self-auth-2
  src/modules/members/members.controller.ts
  src/modules/members/members.service.spec.ts
  src/modules/members/members.service.ts
Labels: 🔨 Refactor

#19 feature/#6-OAuth-google
  src/interfaces/auth.interface.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.google.strategy.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/sign-up.dto.ts
  src/modules/members/dto/create-member.dto.ts
  src/modules/members/members.module.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
  src/shared/helpers/auth.helpers.ts
Labels: ✨ Feature, 🔨 Refactor

#21 ➖ minus(@liaoliaots/nestjs-redis): nestjs-redis 제거
  package.json
  src/modules/app/app.module.ts
  src/modules/redis/redis.module.ts
  src/modules/redis/redis.service.ts
Labels: 🐞 BugFix

#22 feature/#6-OAuth-line
  package.json
  prisma/migrations/20240207190622_update_member_nullable_email/migration.sql
  prisma/migrations/20240207195648_update_member_notunique_nickname/migration.sql
  prisma/schema.prisma
  src/interfaces/auth.interface.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.google.strategy.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.line.strategy.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/oauth-sign-up.dto.ts
  src/modules/members/dto/create-member.dto.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
  src/shared/helpers/auth.helpers.ts
  yarn.lock
Labels: ✨ Feature

#23 Feature/#14 plan search
  package.json
  prisma/schema.prisma
  src/interfaces/google.interface.ts
  src/main.ts
  src/modules/app/app.module.ts
  src/modules/common/http/google-http.service.ts
  src/modules/places/dto/place.dto.ts
  src/modules/places/places.controller.ts
  src/modules/places/places.module.ts
  src/modules/places/places.repository.ts
  src/modules/places/places.service.ts
  yarn.lock
Labels: 📬 API, ✨ Feature

#27 Feature/#14 plan search
  prisma/schema.prisma
  src/interfaces/google.interface.ts
  src/modules/common/http/google-http.service.ts
  src/modules/places/places.repository.ts
  src/modules/places/places.service.ts
Labels: ✨ Feature

#28 feature/#25-guide-register
  package.json
  prisma/migrations/20240209161254_alter_guide_profile_and_related_entities_with_constraints_and_indexes"/migration.sql
  prisma/migrations/20240213155710_add_unique_index_to_board_like_for_board_id_and_member_id/migration.sql
  prisma/migrations/20240213173848_alter_guide_review_add_columns_and_constraints_with_multiple_unique_indexes/migration.sql
  prisma/migrations/20240214114554_alter_place_add_columns_and_create_opening_hours_with_constraints/migration.sql
  prisma/migrations/20240216123151_alter_place_review_add_foreign_key_placeId/migration.sql
  prisma/schema.prisma
  prisma/seeds/area.seed.ts
  prisma/seeds/index.ts
  prisma/seeds/language.seed.ts
  prisma/seeds/member.seed.ts
  src/modules/app/app.module.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.jwt.strategy.ts
  src/modules/auth/auth.module.ts
  src/modules/guides/dto/register-guide.dto.ts
  src/modules/guides/dto/update-areas.dto.ts
  src/modules/guides/dto/update-language-certifications.dto.ts
  src/modules/guides/dto/update-languages.dto.ts
  src/modules/guides/guides.controller.ts
  src/modules/guides/guides.module.ts
  src/modules/guides/guides.repository.ts
  src/modules/guides/guides.service.ts
  src/modules/members/dto/update-language.dto.ts
  src/modules/members/members.controller.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
  src/modules/redis/redis.module.ts
  src/modules/redis/redis.provider.ts
  src/modules/redis/redis.service.ts
  src/shared/constants/error-messages.constants.ts
  yarn.lock
Labels: ✨ Feature

#31 Feature/#30 dockerize
  Dockerfile
  package.json
Labels: 🌏 Deploy

#34 fix/#32-reduce-redis-dependency
  package.json
  src/main.ts
  src/modules/app/app.module.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.google.strategy.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.jwt.strategy.ts
  src/modules/auth/auth.line.strategy.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.repository.ts
  src/modules/common/http/google-http.service.ts
  src/modules/guides/guides.service.ts
  src/modules/places/places.controller.ts
  src/modules/places/places.repository.ts
  src/modules/places/places.service.ts
  src/modules/redis/redis.module.ts
  src/modules/redis/redis.provider.ts
  src/modules/redis/redis.service.ts
  yarn.lock
Labels: 🐞 BugFix, 🔨 Refactor

#36 Feature/#24 direction logic
  src/interfaces/google.interface.ts
  src/interfaces/ortools.interface.ts
  src/modules/app/app.module.ts
  src/modules/common/http/google-http.service.ts
  src/modules/common/http/kakao-http.service.ts
  src/modules/common/http/ortools.service.ts
  src/modules/places/places.repository.ts
  src/plans/plans.controller.ts
  src/plans/plans.module.ts
  src/plans/plans.repository.ts
  src/plans/plans.service.ts
Labels: 📬 API, ✨ Feature

#37 Feature/#24 direction logic
  src/modules/common/http/ortools.service.ts
  src/plans/plans.repository.ts
  src/plans/plans.service.ts
Labels: 🔨 Refactor

#38 fix: 카카오 거리 계산 오류 수정
  src/plans/plans.repository.ts
Labels: 🐞 BugFix

#41 feature/#40-docker-api-ready
  .gitignore
  Dockerfile.dev
  README.md
  docker-compose.dev.yaml
  docker-compose.prod.yaml
  package.json
  src/main.ts
Labels: 🌏 Deploy

#42 feature/#40-docker-api-ready
  docker-compose.yaml
Labels: 🌏 Deploy

#46 fix(eslint): eslint 규칙 수정 (no-unused-vars)
  .eslintrc.js
Labels: 🐞 BugFix

#48 chore/alter-guide-profile-ref
  prisma/migrations/20240223154157_alter_guide_review_id_reference_member_id/migration.sql
  prisma/migrations/20240224061819_alter_guide_profile_rename_temperatrue_to_temperature/migration.sql
  prisma/schema.prisma
  src/modules/guides/guides.repository.ts
Labels: 🔨 Refactor

#54 feature/#43-guide-list-pagination
  src/modules/auth/dto/sign-up.dto.ts
  src/modules/guides/guides.controller.ts
  src/modules/guides/guides.decorator.ts
  src/modules/guides/guides.interface.ts
  src/modules/guides/guides.pipe.ts
  src/modules/guides/guides.repository.ts
  src/modules/guides/guides.service.ts
  src/shared/decorators/pagination.decorator.ts
  src/shared/helpers/date.helpers.ts
  src/shared/pagination/dto/page-request.dto.ts
  src/shared/pagination/dto/page-response.dto.ts
  src/shared/pagination/pagination.interface.ts
  src/shared/pagination/pagination.pipe.ts
  src/shared/pagination/pagination.utils.ts
Labels: ✨ Feature
