Repository THE-FIRST-DANCE/soomga-backend, pull requests merged in 2024-04, with the labels that each got.

#86 chore(prefix): 모든 라우트에 기본경로 설정 `api`
  src/main.ts
Labels: 🔨 Refactor

#88 Feature/#83 sos
  prisma/migrations/20240402013304_/migration.sql
  prisma/schema.prisma
  src/interfaces/boards.interface.ts
  src/modules/boards/sos/dto/comment.dto.ts
  src/modules/boards/sos/dto/create-sos.dto.ts
  src/modules/boards/sos/sos.controller.ts
  src/modules/boards/sos/sos.repository.ts
  src/modules/boards/sos/sos.service.ts
  src/modules/common/http/ortools.service.ts
  src/modules/events/dto/events.dto.ts
  src/modules/events/events.repository.ts
  src/shared/boards/dto/create-board.dto.ts
Labels: 📬 API, ✨ Feature

#90 Feature/#89 push notification
  package.json
  prisma/schema.prisma
  src/modules/boards/boards.module.ts
  src/modules/boards/sos/sos.repository.ts
  src/modules/boards/trips/trips.repository.ts
  src/modules/notification/notification.service.ts
  yarn.lock
Labels: ✨ Feature

#92 Feature/#91 generate erd with prisma
  .github/ISSUE_TEMPLATE/개선-이슈.md
  .gitignore
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: ✨ Feature

#94 refactor(guide_pagination): 가이드 페이지네이션 조회 구조 변경, 점수가 정상적으로 조회안되었던 것 수정
  src/modules/guides/guides.interface.ts
  src/modules/guides/guides.repository.ts
Labels: 🐞 BugFix, 🔨 Refactor

#96 Refactor/#95 delete migrations
  prisma/migrations/20240201103833_init/migration.sql
  prisma/migrations/20240202051746_update_member_add_birthdate/migration.sql
  prisma/migrations/20240206115541_update_member_add_oauth_provider/migration.sql
  prisma/migrations/20240206125230_update_member_add_avatar/migration.sql
  prisma/migrations/20240207190622_update_member_nullable_email/migration.sql
  prisma/migrations/20240207195648_update_member_notunique_nickname/migration.sql
  prisma/migrations/20240209161254_alter_guide_profile_and_related_entities_with_constraints_and_indexes"/migration.sql
  prisma/migrations/20240213155710_add_unique_index_to_board_like_for_board_id_and_member_id/migration.sql
  prisma/migrations/20240213173848_alter_guide_review_add_columns_and_constraints_with_multiple_unique_indexes/migration.sql
  prisma/migrations/20240214114554_alter_place_add_columns_and_create_opening_hours_with_constraints/migration.sql
  prisma/migrations/20240216123151_alter_place_review_add_foreign_key_placeId/migration.sql
  prisma/migrations/20240223154157_alter_guide_review_id_reference_member_id/migration.sql
  prisma/migrations/20240224061819_alter_guide_profile_rename_temperatrue_to_temperature/migration.sql
  prisma/migrations/20240307105638_update_pivot_tables_to_composite_key/migration.sql
  prisma/migrations/20240307122759_update_rename_acess_status_to_access_status/migration.sql
  prisma/migrations/20240318110634_update_chatroom_pk_ai_to_uuid/migration.sql
  prisma/migrations/20240319024919_update_chatroom_message_pk_uuid_to_aikey/migration.sql
  prisma/migrations/20240328053622_update_boards_add_url_unique_key_and_file_schema/migration.sql
  prisma/migrations/20240328080829_update_url_add_unique_key_to_file/migration.sql
  prisma/migrations/20240402013304_/migration.sql
Labels: 🔨 Refactor

#101 feature/#100-crud_areas
  src/modules/app/app.module.ts
  src/modules/areas/areas.controller.ts
  src/modules/areas/areas.module.ts
  src/modules/areas/areas.repository.ts
  src/modules/areas/areas.service.ts
Labels: ✨ Feature

#98 refactor/#97-pagination_int_array
  src/modules/guides/guides.decorator.ts
  src/shared/pagination/pagination.pipe.ts
Labels: 🔨 Refactor

#103 feature/#99-guide_review
  src/modules/guides/dto/create-review.dto.ts
  src/modules/guides/dto/update-review.dto.ts
  src/modules/guides/guides.controller.ts
  src/modules/guides/guides.decorator.ts
  src/modules/guides/guides.interface.ts
  src/modules/guides/guides.repository.ts
  src/modules/guides/guides.service.ts
Labels: ✨ Feature, 🔨 Refactor

#105 fix/#104-add_error_message_exception
  src/shared/constants/error-messages.constants.ts
Labels: 🐞 BugFix

#110 fix(guide_pagination): 점수 필터링 로직 수정
  src/modules/guides/guides.repository.ts
  src/shared/pagination/dto/page-response.dto.ts
  src/shared/pagination/pagination.utils.ts
Labels: 🐞 BugFix

#111 feature/#107-follow
  prisma/schema.prisma
  src/modules/boards/sos/dto/create-sos.dto.ts
  src/modules/events/dto/events.dto.ts
  src/modules/guides/guides.interface.ts
  src/modules/guides/guides.repository.ts
  src/modules/members/members.controller.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
  src/modules/mypage/mypage.controller.ts
  src/modules/mypage/mypage.service.ts
  src/shared/boards/dto/create-board.dto.ts
Labels: ✨ Feature

#114 🐛 fix(pagination): items가 없을 시, return null
  src/modules/guides/guides.interface.ts
  src/shared/pagination/pagination.utils.ts
Labels: 🐞 BugFix

#115 Feature/#93 trips
  prisma/schema.prisma
  src/modules/boards/sos/sos.controller.ts
  src/modules/boards/trips/trips.controller.ts
  src/modules/boards/trips/trips.repository.ts
  src/modules/boards/trips/trips.service.ts
  src/pipes/ParseIntArrayPipe.service.ts
Labels: ✨ Feature

#121 feat(schema): `Service`, `Reservation` 모델 추가
  prisma/schema.prisma
Labels: ✨ Feature

#122 feature/#120-crud_service
  package.json
  prisma/schema.prisma
  src/configs/config.interface.ts
  src/configs/env-validate.schema.ts
  src/configs/global.config.ts
  src/interfaces/chat.interface.ts
  src/modules/app/app.module.ts
  src/modules/aws/aws.service.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.module.ts
  src/modules/chat/chat.repository.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/update-room.dto.ts
  src/modules/guides/dto/update-profile.dto.ts
  src/modules/guides/guides.controller.ts
  src/modules/guides/guides.repository.ts
  src/modules/guides/guides.service.ts
  src/modules/members/members.controller.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
  src/modules/reservations/dto/create-reservation.ts
  src/modules/reservations/dto/update-reservation.ts
  src/modules/reservations/reservations.controller.ts
  src/modules/reservations/reservations.module.ts
  src/modules/reservations/reservations.repository.ts
  src/modules/reservations/reservations.service.ts
  src/modules/services/dto/create-services.dto.ts
  src/modules/services/dto/update-service.dto.ts
  src/modules/services/services.controller.ts
  src/modules/services/services.module.ts
  src/modules/services/services.repository.ts
  src/modules/services/services.service.ts
  src/modules/uploads/uploads.service.ts
  src/shared/constants/error-messages.constants.ts
  yarn.lock
Labels: ✨ Feature

#127 Feature/#117 plan plus
  prisma/schema.prisma
  src/modules/aws/aws.service.ts
  src/modules/boards/trips/dto/create-trip.dto.ts
  src/modules/boards/trips/trips.controller.ts
  src/modules/boards/trips/trips.repository.ts
  src/modules/boards/trips/trips.service.ts
  src/modules/common/http/google-http.service.ts
  src/modules/guides/guides.repository.ts
  src/modules/notification/notification.service.ts
  src/modules/places/places.controller.ts
  src/modules/places/places.module.ts
  src/modules/places/places.repository.ts
  src/modules/places/places.service.ts
  src/modules/plans/dto/plans.dto.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.repository.ts
  src/modules/plans/plans.service.ts
  src/shared/boards/dto/create-board.dto.ts
Labels: ✨ Feature, 🔨 Refactor
