Repository THE-FIRST-DANCE/soomga-backend, pull requests merged in 2024-03, with the labels that each got.

#47 Feature/#39 plan save edit
  prisma/schema.prisma
  src/interfaces/google.interface.ts
  src/plans/dto/plans.dto.ts
  src/plans/plans.controller.ts
  src/plans/plans.repository.ts
  src/plans/plans.service.ts
Labels: ✨ Feature

#60 fix/#59-prisma-client-debug-error
  src/modules/prisma/prisma.config.ts
  src/modules/prisma/prisma.service.ts
Labels: 🐞 BugFix

#61 chore/change-oauth-callbackURL
  src/modules/auth/auth.google.strategy.ts
  src/modules/auth/auth.line.strategy.ts
Labels: 🔨 Refactor

#64 feature/seeds
  prisma/migrations/20240307122759_update_rename_acess_status_to_access_status/migration.sql
  prisma/schema.prisma
  prisma/seeds/area.seed.ts
  prisma/seeds/common.interface.ts
  prisma/seeds/default-member.seed.ts
  prisma/seeds/guide.seed.ts
  prisma/seeds/index.ts
  prisma/seeds/language.seed.ts
  prisma/seeds/member.seed.ts
  prisma/seeds/utils.ts
Labels: ✨ Feature

#66 feature/#65-admin-management
  src/modules/admin/admin.controller.spec.ts
  src/modules/admin/admin.controller.ts
  src/modules/admin/admin.module.ts
  src/modules/admin/admin.service.spec.ts
  src/modules/admin/admin.service.ts
  src/modules/admin/dto/active-members.dto.ts
  src/modules/admin/dto/delete-members.dto.ts
  src/modules/admin/dto/inactive-members.dto.ts
  src/modules/admin/dto/member-status.dto.ts
  src/modules/app/app.module.ts
Labels: ✨ Feature

#67 chore(exceptions): 사용하지 않는 exception 삭제
  src/exceptions/member.exception.ts
Labels: ✨ Feature

#70 feat(consants): authorization에서 발생하는 권한 문제에 대한 에러메시지 추가
  src/shared/constants/error-messages.constants.ts
Labels: ✨ Feature

#72 feature/#65-admin-management-2
  src/modules/members/members.controller.ts
  src/modules/members/members.repository.ts
  src/modules/members/members.service.ts
Labels: ✨ Feature

#74 Feature/#71 schedule
  prisma/schema.prisma
  src/modules/app/app.module.ts
  src/modules/events/dto/events.dto.ts
  src/modules/events/events.controller.ts
  src/modules/events/events.module.ts
  src/modules/events/events.repository.ts
  src/modules/events/events.service.ts
  src/modules/places/places.controller.ts
  src/modules/places/places.repository.ts
  src/plans/plans.controller.ts
  src/plans/plans.repository.ts
  src/plans/plans.service.ts
Labels: ✨ Feature

#77 fix/#76-plans_module_to_modules_directory
  src/modules/app/app.module.ts
  src/modules/plans/dto/plans.dto.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/plans.repository.ts
  src/modules/plans/plans.service.ts
Labels: 🐞 BugFix

#79 Refactor/#78 socket with redis
  docker-compose.dev.yaml
  docker-compose.prod.yaml
  docker-compose.yaml
  package.json
  src/main.ts
  src/modules/chat/chat.gateway.ts
  src/modules/redis/redis.adapter.ts
  yarn.lock
Labels: 🔨 Refactor

#81 feature/#80-boards
  prisma/seeds/index.ts
  prisma/seeds/language.seed.ts
  prisma/seeds/member.seed.ts
  prisma/seeds/tag.seed.ts
  src/interfaces/boards.interface.ts
  src/modules/app/app.module.ts
  src/modules/boards/boards.module.ts
  src/modules/boards/sos/dto/create-sos.dto.ts
  src/modules/boards/sos/dto/update-sos.dto.ts
  src/modules/boards/sos/sos.controller.ts
  src/modules/boards/sos/sos.decorator.ts
  src/modules/boards/sos/sos.repository.ts
  src/modules/boards/sos/sos.service.ts
  src/modules/boards/trips/dto/create-trip.dto.ts
  src/modules/boards/trips/dto/update-trip.dto.ts
  src/modules/boards/trips/trips.controller.ts
  src/modules/boards/trips/trips.repository.ts
  src/modules/boards/trips/trips.service.ts
  src/modules/members/dto/update-tags.dto.ts
  src/modules/tags/tags.controller.spec.ts
  src/modules/tags/tags.controller.ts
  src/modules/tags/tags.module.ts
  src/modules/tags/tags.repository.ts
  src/modules/tags/tags.service.spec.ts
  src/modules/tags/tags.service.ts
  src/shared/boards/dto/create-board.dto.ts
  src/shared/boards/dto/update-board.dto.ts
Labels: ✨ Feature
